DARES = [
    "Do 20 push-ups right now and send proof!",
    "Send a funny selfie to the group.",
    "Speak in an accent for the next 3 messages.",
    "Do your best dance and describe it in detail.",
    "Send a voice message singing your favorite song.",
    "Change your group profile picture to something funny.",
    "Let the person above you write your status for 24 hours.",
    "Do 30 jumping jacks and send a video!",
    "Imitate another group member (describe in detail).",
    "Share your most embarrassing photo.",
    "Talk in rhymes for the next 5 messages.",
    "Do your best celebrity impression in text.",
    "Send a message to your crush (screenshot it!).",
    "Post a throwback photo from 5+ years ago.",
    "Let someone else choose your profile picture for a week.",
    "Write a funny poem about someone in the group.",
    "Share the last photo in your gallery.",
    "Do 50 jumping jacks.",
    "Share your screen time report.",
    "Send a meme that describes your life right now.",
    "Text your mom 'I love you' right now.",
    "Do 10 burpees and send proof.",
    "Share an embarrassing voice note.",
    "Let someone send a text from your phone.",
    "Post a story saying 'I lost a bet'.",
    "Text your most recent contact 'we need to talk' and screenshot their reply.",
    "Change your bio to something embarrassing for the next 2 hours.",
    "Do your best impression of a news anchor for 3 sentences.",
    "Send a voice message saying 'I am the greatest' with full confidence.",
    "Let someone in the group pick your next profile photo for 48 hours.",
    "Send a 'good morning' text to the last 5 people in your contacts.",
    "Do 15 squats and narrate each one dramatically.",
    "Post a blurry photo and caption it 'memories'.",
    "Text someone 'I have a confession' and then say something completely boring.",
    "Write a 5-star review of your own personality right now.",
    "Describe your last meal like a food critic and send it to the group.",
    "Call someone and say 'I think there's something you should know' then hang up.",
    "Send a voice note doing a dramatic reading of your last text conversation.",
    "Wear something on your head for the next 30 minutes and send proof.",
    "Text someone a random fact about penguins with zero context.",
    "Write a professional LinkedIn post about something embarrassing you did.",
    "Let the group pick your next story post content.",
    "Send the most unflattering selfie you can take right now.",
    "Call a friend and narrate everything you see like a nature documentary.",
    "Set your alarm to ring every hour tonight and prove it by sending your alarm list.",
    "Send a voice note in a British accent asking someone how their day was.",
    "Text your sibling or parent a ridiculously formal business email.",
    "Do your best robot impression in a voice message.",
    "Post a story asking people to rate your cooking 1–10 (based on nothing).",
    "Take a photo of the inside of your fridge and send it with a critique.",
    "Text someone 'I need help' and describe the most minor inconvenience you're facing.",
    "Record yourself eating a snack as dramatically as possible.",
    "Change your ringtone to something embarrassing for 24 hours and send proof.",
    "Send a compliment to every person in this group (one message each).",
    "Do 10 push-ups in the most over-dramatic way possible and describe each one.",
]
