FATES = [
    "Your future holds... absolutely nothing impressive. But hey, at least you tried!",
    "You will find true love... right after you stop looking in the mirror so much.",
    "A great opportunity awaits you... to embarrass yourself in public. Again.",
    "Your destiny is to become legendary... at procrastination.",
    "Fortune favors the bold. Unfortunately, you're not bold, just loud.",
    "You will soon receive unexpected money... which you'll immediately waste on something stupid.",
    "A mysterious stranger will change your life... by blocking you on social media.",
    "Your dreams will come true... but only the embarrassing ones.",
    "Success is in your future... if you redefine what 'success' means.",
    "You will live a long and happy life... in your imagination.",
    "A big change is coming... you'll finally update your profile picture from 2015.",
    "Your destiny is to inspire others... to not be like you.",
    "The stars say you'll find wisdom... but they're probably talking about someone else.",
    "Great wealth is in your future... in Monopoly money.",
    "You will travel the world... via Google Maps street view.",
    "Your future is bright... unlike your decision-making skills.",
    "A surprise awaits you... it's the consequences of your actions.",
    "You will achieve greatness... at being average.",
    "The universe has big plans for you... mostly as a cautionary tale.",
    "Your fate is sealed... with duct tape and bad choices.",
    "You will meet your soulmate... they'll reject you, but you'll meet them!",
    "Success will knock on your door... but you'll be in the bathroom and miss it.",
    "Your future holds adventure... like finding a good parking spot.",
    "You will be remembered... for that one embarrassing thing you did.",
    "Destiny awaits... it's just stuck in traffic right now.",
    "The cosmos predict... you'll spend way too much time on your phone today.",
    "Your fortune says... you'll find something you lost. It was in your hand the whole time.",
    "A prophecy foretold... you'll accidentally like someone's old post while stalking them.",
    "The stars align to reveal... you'll eat way more pizza than you planned.",
    "Your destiny is written... in autocorrect fails and typos.",
    "The cosmos have consulted... and asked to reschedule you for a later date.",
    "Your destiny involves great power... specifically, the power button on your TV remote.",
    "A breakthrough moment awaits you... it's when you finally read the full terms and conditions.",
    "Fortune sees you rising to great heights... specifically the 2nd floor, because the lift is broken.",
    "The stars predict a long and fruitful journey... through the IKEA checkout queue.",
    "You will achieve something no one expected... mostly because no one expected anything.",
    "Your fate is sealed... in a plastic bag from a shop that no longer exists.",
    "Great wisdom will find you... but it's going to take the scenic route getting there.",
    "The universe is preparing something special for you... it's buffering. Please wait.",
    "Your future holds passion and fire... mostly from the microwave meal you forgot to stir.",
    "Prosperity awaits you... it's the one coin you'll find in an old jacket pocket.",
    "The stars see an adventurous spirit in you... mostly because you took a wrong turn and refuse to admit it.",
    "Your legacy will be remembered... for at least 3–4 business days.",
    "A new chapter begins... it's mostly just you having the same bad habits in a different font.",
    "The heavens declare your potential is limitless... which is lucky because your results have been quite limited so far.",
    "You will master the art of communication... right after you reply to those 47 unopened messages.",
    "A prophecy foretells... you will watch 'just one more episode' and then lie about how many you watched.",
    "Greatness is just around the corner... unfortunately you keep walking past it.",
    "Your destiny is to inspire the world... to double-check their work before submitting.",
    "The oracle sees a sudden windfall... it's three unused vouchers that expire tomorrow.",
    "Fortune smiles upon you... mostly in a 'bless their heart' kind of way.",
    "You are destined for great love... your Wi-Fi connection will finally be stable.",
    "The universe confirms: you are unique... like every other person it's told that to.",
    "A grand revelation approaches... you'll finally understand that one joke from three years ago.",
    "Your aura radiates success... it's mostly the phone brightness you forgot to turn down.",
    "The fates reveal a passionate career ahead... in telling people about things they didn't ask about.",
    "Cosmic forces align in your favour... they're arguing about it but they'll reach a consensus soon.",
    "You are on the precipice of something huge... it's mostly your credit card bill.",
    "The stars predict unexpected travel... you'll take the wrong bus and discover a new neighbourhood.",
    "Your fortune is written in the stars... unfortunately the stars are currently experiencing technical difficulties.",
]
