ROASTS = [
    "You're not stupid, you just have bad luck when thinking.",
    "I'd agree with you, but then we'd both be wrong.",
    "You're like a software update. Whenever I see you, I think 'not now.'",
    "If laughter is the best medicine, your face must be curing the world.",
    "You're the reason the gene pool needs a lifeguard.",
    "I'm not saying you're dumb, but you've got the survival instincts of a dodo bird.",
    "You bring everyone so much joy... when you leave the room.",
    "Your secrets are safe with me. I wasn't even listening.",
    "You're not the dumbest person in the world, but you better hope they don't die.",
    "I'd challenge you to a battle of wits, but I see you came unarmed.",
    "You're like a cloud. When you disappear, it's a beautiful day.",
    "I'm jealous of people who haven't met you yet.",
    "You're proof that evolution can go in reverse.",
    "If you were any more inbred, you'd be a sandwich.",
    "You're the human version of a participation trophy.",
    "Somewhere out there is a tree tirelessly producing oxygen for you. Go apologize to it.",
    "You're like Monday mornings - nobody likes you.",
    "I'd give you a nasty look, but you've already got one.",
    "You're not lazy, you're just on energy-saving mode... permanently.",
    "You have the perfect face for radio.",
    "If brains were dynamite, you wouldn't have enough to blow your nose.",
    "You're the reason God created the middle finger.",
    "I'd roast you, but my mom says I'm not allowed to burn trash.",
    "You're like a plunger - you bring up old crap that nobody wants to see.",
    "I would ask how old you are, but I know you can't count that high.",
    "You're so fake, even China denied making you.",
    "I'm not insulting you, I'm just describing you.",
    "You're the reason why shampoo has instructions.",
    "If I had a face like yours, I'd sue my parents.",
    "You're about as useful as a screen door on a submarine.",
    "You're like a participation trophy — everyone got one, nobody asked for it.",
    "I'd say you're the smartest person in the room, but I'm also in the room.",
    "You have the confidence of someone who's never once been wrong, and the track record of someone who always is.",
    "Calling you average would be a serious compliment to your potential.",
    "You're like WiFi in the countryside — occasionally there, mostly disappointing.",
    "Your vibe is aggressively mid and I respect your commitment to it.",
    "I've seen sharper tools in a spoon drawer.",
    "You're not the worst person I know, but you're definitely in the top five.",
    "You have the energy of a half-charged phone that someone forgot to plug in.",
    "You're like a pop-up ad — nobody sent for you but here you are.",
    "I'd call you a clown but clowns actually make people happy.",
    "Your presence is felt the same way a headache is.",
    "You're the kind of person who texts 'k' and thinks they've been helpful.",
    "Somewhere, a village is missing an optimist, and it's definitely not you.",
    "You have big 'sent the email to the wrong person and didn't notice' energy.",
    "You're proof that confidence and competence are two completely different things.",
    "I'd roast your personality but I'd need something to work with first.",
    "You're the human equivalent of stepping on Lego — painful and totally avoidable.",
    "You remind me of a Monday morning that also had bad news in it.",
    "I'd say you were born ahead of your time, but I don't think time wants you either.",
    "You have the social awareness of a car alarm at 3am.",
    "You're the reason people put 'must have common sense' in job listings.",
    "You're like a group project — everyone does the work and you show up for the photo.",
    "You speak with such authority for someone who's been wrong this many times.",
    "If confusion were currency, you'd be incredibly wealthy.",
    "I'm not saying you're forgettable, but I keep having to re-introduce myself.",
    "You have the emotional range of a brick, but with less structural usefulness.",
    "You're the type to Google something, read the first sentence, and become an expert.",
    "You have the energy of someone who argues with automated phone systems.",
    "You're not a bad person. You're just exhausting in a very specific and consistent way.",
]
