TRUTHS = [
    "What's the most embarrassing thing you've ever done?",
    "What's your biggest fear?",
    "Have you ever told a lie to get out of trouble?",
    "What's the worst gift you've ever received?",
    "Who was your first crush?",
    "What's something you've never told anyone?",
    "What's your most embarrassing childhood memory?",
    "Have you ever cheated on a test?",
    "What's the biggest lie you've ever told?",
    "What's your guilty pleasure?",
    "Who in this group do you trust the most?",
    "What's the most childish thing you still do?",
    "Have you ever stalked someone on social media?",
    "What's your biggest insecurity?",
    "What's the worst date you've ever been on?",
    "If you could swap lives with someone for a day, who would it be?",
    "What's the most trouble you've been in?",
    "Have you ever ghosted someone?",
    "What's your most unpopular opinion?",
    "What's the craziest dream you've ever had?",
    "What's the most embarrassing thing in your search history?",
    "Who was your worst kiss?",
    "What's your biggest regret?",
    "Have you ever pretended to be sick to skip something?",
    "What's the longest you've gone without showering?",
    "What's the most embarrassing thing you've texted the wrong person?",
    "Have you ever pretended to laugh at a joke you didn't understand?",
    "What's the most ridiculous reason you've cried?",
    "Have you ever liked someone's old photo while stalking their profile?",
    "What's the pettiest thing you've ever done to get revenge?",
    "Have you ever blamed someone else for something you did?",
    "What's the most embarrassing thing your parents have caught you doing?",
    "Have you ever sent a risky text and immediately regretted it?",
    "What's the weirdest thing you've Googled at 3am?",
    "Have you ever faked being sick just to avoid someone specific?",
    "What's the most money you've wasted on something completely useless?",
    "Have you ever read someone's diary or personal messages without permission?",
    "What's the most embarrassing thing you've said during a job interview?",
    "Have you ever eaten food that fell on the floor and told no one?",
    "What's the biggest secret you're keeping from your family?",
    "Have you ever walked into the wrong bathroom and not immediately left?",
    "What's the most desperate thing you've done to get someone's attention?",
    "Have you ever laughed at a completely inappropriate moment?",
    "What's the most childish argument you've had with an adult?",
    "Have you ever pretended to know someone you completely forgot?",
    "What's the worst thing you've ever said in your sleep (if you know)?",
    "Have you ever been caught talking to yourself in public?",
    "What's the most embarrassing song in your most-played list?",
    "Have you ever accidentally called a teacher 'mom' or 'dad'?",
    "What's the longest you've procrastinated something truly important?",
    "Have you ever sent a flirty text to the wrong person?",
    "What's the most embarrassing nickname you've ever had?",
    "Have you ever cried at something that was definitely not meant to be sad?",
    "What's the weirdest habit you have that nobody knows about?",
    "Have you ever pretended to be busy just to avoid replying to someone?",
]

