WOULD_YOU_RATHER = [
    "Would you rather always speak in slow motion or always move in fast forward?",
    "Would you rather have everything you eat taste like broccoli or have everything smell like petrol?",
    "Would you rather have no eyebrows or one giant unibrow you can't shave?",
    "Would you rather be able to pause time but never sleep or sleep 20 hours a day but never pause anything?",
    "Would you rather accidentally send your search history to your boss or your mom?",
    "Would you rather fart every time you laugh or burp every time you lie?",
    "Would you rather only be able to whisper or only be able to shout?",
    "Would you rather have your deepest fear exposed to everyone or your biggest crush announced publicly?",
    "Would you rather have a permanent 'buffering' symbol over your face or a like/dislike counter?",
    "Would you rather sneeze every time you try to kiss someone or hiccup every time you try to sleep?",
    "Would you rather swap voices with your best friend for a month or swap phones for a week?",
    "Would you rather always have sand in your shoes or always have a wet sleeve?",
    "Would you rather only be able to eat hot food that's cold or cold food that's hot?",
    "Would you rather have your texts autocorrected to Shakespeare or spoken aloud by a robot?",
    "Would you rather forget every dream you have or remember every dream in painful detail?",
    "Would you rather have everyone hear your inner monologue for one day or have your entire text history read aloud to your family?",
    "Would you rather be stuck in an elevator with your ex or your most awkward distant relative?",
    "Would you rather have a laugh that sounds like a goat or a sneeze that sounds like a foghorn?",
    "Would you rather lose the ability to use sarcasm or lose the ability to use emojis forever?",
    "Would you rather always arrive 2 hours early or always show up exactly 30 minutes late?",
    "Would you rather have your most embarrassing moment played on a loop at your workplace or your hometown?",
    "Would you rather never be able to delete a message or never be able to mute a notification?",
    "Would you rather eat cereal with orange juice or eat pasta with milk?",
    "Would you rather trip in front of your crush once or make a typo in a group chat every day for a year?",
    "Would you rather always have to explain every joke you make or never be able to laugh at jokes?",
    "Would you rather have unlimited battery on your phone or never feel tired ever again?",
    "Would you rather have skin that changes color based on your mood or hair that grows 2cm every hour?",
    "Would you rather know the exact time you'll die or never know but it could be any second?",
    "Would you rather spend a week as your most annoying coworker or a month as your most boring relative?",
    "Would you rather only be able to walk sideways or only be able to run, never walk at speed?",
    "Would you rather fight 100 duck-sized horses or 1 horse-sized duck?",
    "Would you rather always have to sing instead of speak or dance everywhere you go?",
    "Would you rather have a rewind button or a pause button for your life?",
    "Would you rather be able to talk to animals or speak all human languages?",
    "Would you rather have unlimited bacon but no more games, or unlimited games but no more bacon?",
    "Would you rather sweat mayo or have your armpits smell like onions?",
    "Would you rather have a mullet for a year or be bald for 6 months?",
    "Would you rather always have to enter rooms backwards or always have to somersault out?",
    "Would you rather have fingers as long as your legs or legs as short as your fingers?",
    "Would you rather fight Mike Tyson once or talk like him forever?",
    "Would you rather lose all your teeth or lose all your hair?",
    "Would you rather have a third nipple or an extra toe?",
    "Would you rather always wear wet socks or always have a small rock in your shoe?",
    "Would you rather have to sneeze but not be able to, or have something stuck in your eye for an entire year?",
    "Would you rather be forced to dance every time you hear music or be forced to sing along to any song you hear?",
    "Would you rather have a permanently clogged nose or a piece of green spinach stuck in your teeth forever?",
    "Would you rather communicate only in emojis or never be able to use emojis again?",
    "Would you rather have your browser history made public or your bank balance displayed on your forehead?",
    "Would you rather always have to say everything on your mind or never speak again?",
    "Would you rather eat a raw onion or a raw potato?",
    "Would you rather have your thoughts appear in text bubbles above your head or have everything you think come true?",
    "Would you rather be itchy for the rest of your life or sticky for the rest of your life?",
    "Would you rather have Cheetos dust on your fingers forever or have a popcorn kernel stuck in your teeth forever?",
    "Would you rather speak in rhymes for the rest of your life or only be able to speak in questions?",
    "Would you rather have to wear clown shoes every day or a clown wig every day?",
    "Would you rather always speak in slow motion or always move in fast forward?",
    "Would you rather have everything you eat taste like broccoli or have everything smell like petrol?",
    "Would you rather have no eyebrows or one giant unibrow you can't shave?",
    "Would you rather be able to pause time but never sleep or sleep 20 hours a day but never pause anything?",
    "Would you rather accidentally send your search history to your boss or your mom?",
    "Would you rather fart every time you laugh or burp every time you lie?",
    "Would you rather only be able to whisper or only be able to shout?",
    "Would you rather have your deepest fear exposed to everyone or your biggest crush announced publicly?",
    "Would you rather have a permanent 'buffering' symbol over your face or a like/dislike counter?",
    "Would you rather sneeze every time you try to kiss someone or hiccup every time you try to sleep?",
    "Would you rather swap voices with your best friend for a month or swap phones for a week?",
    "Would you rather always have sand in your shoes or always have a wet sleeve?",
    "Would you rather only be able to eat hot food that's cold or cold food that's hot?",
    "Would you rather have your texts autocorrected to Shakespeare or spoken aloud by a robot?",
    "Would you rather forget every dream you have or remember every dream in painful detail?",
    "Would you rather have everyone hear your inner monologue for one day or have your entire text history read aloud to your family?",
    "Would you rather be stuck in an elevator with your ex or your most awkward distant relative?",
    "Would you rather have a laugh that sounds like a goat or a sneeze that sounds like a foghorn?",
    "Would you rather lose the ability to use sarcasm or lose the ability to use emojis forever?",
    "Would you rather always arrive 2 hours early or always show up exactly 30 minutes late?",
    "Would you rather have your most embarrassing moment played on a loop at your workplace or your hometown?",
    "Would you rather never be able to delete a message or never be able to mute a notification?",
    "Would you rather eat cereal with orange juice or eat pasta with milk?",
    "Would you rather trip in front of your crush once or make a typo in a group chat every day for a year?",
    "Would you rather always have to explain every joke you make or never be able to laugh at jokes?",
    "Would you rather have unlimited battery on your phone or never feel tired ever again?",
    "Would you rather have skin that changes color based on your mood or hair that grows 2cm every hour?",
    "Would you rather know the exact time you'll die or never know but it could be any second?",
    "Would you rather spend a week as your most annoying coworker or a month as your most boring relative?",
    "Would you rather only be able to walk sideways or only be able to run, never walk at speed?",
]
